### ISSUE TITLE
Comet installation fails

### ISSUE THREAD

**Issue by Denis-Kazakov** [Unbabel/COMET#224]
## 🐛 Bug

pip install unbabel-comet failed on a Linux Mint computer. It installed a number of packages but eventually failed. Please see the full output a the end.
 
### To Reproduce 

I created a new conda environment with a few basic packages (pandas, jupyter lab, matplotlib, tqdm).
Pip was upgraded with the following:
pip install --upgrade pip

### Environment
OS: Linux Mint
Packaging: conda 24.5.0

### Additional context
Full output:
(comet) denis@dslaptop:~$ pip install unbabel-comet
Collecting unbabel-comet
  Downloading unbabel_comet-2.2.2-py3-none-any.whl.metadata (15 kB)
Collecting entmax<2.0,>=1.1 (from unbabel-comet)
  Downloading entmax-1.3-py3-none-any.whl.metadata (348 bytes)
Collecting huggingface-hub<1.0,>=0.19.3 (from unbabel-comet)
  Downloading huggingface_hub-0.24.1-py3-none-any.whl.metadata (13 kB)
Collecting jsonargparse==3.13.1 (from unbabel-comet)
  Downloading jsonargparse-3.13.1-py3-none-any.whl.metadata (55 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 55.5/55.5 kB 605.1 kB/s eta 0:00:00
Requirement already satisfied: numpy<2.0.0,>=1.20.0 in ./miniconda3/envs/comet/lib/python3.12/site-packages (from unbabel-comet) (1.26.4)
Requirement already satisfied: pandas>=1.4.1 in ./miniconda3/envs/comet/lib/python3.12/site-packages (from unbabel-comet) (2.2.2)
Collecting protobuf<5.0.0,>=4.24.4 (from unbabel-comet)
  Downloading protobuf-4.25.3-cp37-abi3-manylinux2014_x86_64.whl.metadata (541 bytes)
Collecting pytorch-lightning<3.0.0,>=2.0.0 (from unbabel-comet)
  Downloading pytorch_lightning-2.3.3-py3-none-any.whl.metadata (21 kB)
Collecting sacrebleu<3.0.0,>=2.0.0 (from unbabel-comet)
  Downloading sacrebleu-2.4.2-py3-none-any.whl.metadata (58 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 58.0/58.0 kB 813.5 kB/s eta 0:00:00
Collecting scipy<2.0.0,>=1.5.4 (from unbabel-comet)
  Downloading scipy-1.14.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (60 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.8/60.8 kB 880.4 kB/s eta 0:00:00
Collecting sentencepiece<0.2.0,>=0.1.96 (from unbabel-comet)
  Downloading sentencepiece-0.1.99.tar.gz (2.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.6/2.6 MB 1.3 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Collecting torch>=1.6.0 (from unbabel-comet)
  Using cached torch-2.3.1-cp312-cp312-manylinux1_x86_64.whl.metadata (26 kB)
Collecting torchmetrics<0.11.0,>=0.10.2 (from unbabel-comet)
  Downloading torchmetrics-0.10.3-py3-none-any.whl.metadata (15 kB)
Collecting transformers<5.0,>=4.17 (from unbabel-comet)
  Downloading transformers-4.43.1-py3-none-any.whl.metadata (43 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.7/43.7 kB 1.1 MB/s eta 0:00:00
Requirement already satisfied: PyYAML>=3.13 in ./miniconda3/envs/comet/lib/python3.12/site-packages (from jsonargparse==3.13.1->unbabel-comet) (6.0.1)
Collecting filelock (from huggingface-hub<1.0,>=0.19.3->unbabel-comet)
  Downloading filelock-3.15.4-py3-none-any.whl.metadata (2.9 kB)
Collecting fsspec>=2023.5.0 (from huggingface-hub<1.0,>=0.19.3->unbabel-comet)
  Downloading fsspec-2024.6.1-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: packaging>=20.9 in ./miniconda3/envs/comet/lib/python3.12/site-packages (from huggingface-hub<1.0,>=0.19.3->unbabel-comet) (24.1)
Requirement already satisfied: requests in ./miniconda3/envs/comet/lib/python3.12/site-packages (from huggingface-hub<1.0,>=0.19.3->unbabel-comet) (2.32.3)
Requirement already satisfied: tqdm>=4.42.1 in ./miniconda3/envs/comet/lib/python3.12/site-packages (from huggingface-hub<1.0,>=0.19.3->unbabel-comet) (4.66.4)
Requirement already satisfied: typing-extensions>=3.7.4.3 in ./miniconda3/envs/comet/lib/python3.12/site-packages (from huggingface-hub<1.0,>=0.19.3->unbabel-comet) (4.12.2)
Requirement already satisfied: python-dateutil>=2.8.2 in ./miniconda3/envs/comet/lib/python3.12/site-packages (from pandas>=1.4.1->unbabel-comet) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in ./miniconda3/envs/comet/lib/python3.12/site-packages (from pandas>=1.4.1->unbabel-comet) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in ./miniconda3/envs/comet/lib/python3.12/site-packages (from pandas>=1.4.1->unbabel-comet) (2023.3)
Collecting lightning-utilities>=0.10.0 (from pytorch-lightning<3.0.0,>=2.0.0->unbabel-comet)
  Downloading lightning_utilities-0.11.6-py3-none-any.whl.metadata (5.2 kB)
Collecting portalocker (from sacrebleu<3.0.0,>=2.0.0->unbabel-comet)
  Downloading portalocker-2.10.1-py3-none-any.whl.metadata (8.5 kB)
Collecting regex (from sacrebleu<3.0.0,>=2.0.0->unbabel-comet)
  Using cached regex-2024.5.15-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (40 kB)
Collecting tabulate>=0.8.9 (from sacrebleu<3.0.0,>=2.0.0->unbabel-comet)
  Using cached tabulate-0.9.0-py3-none-any.whl.metadata (34 kB)
Requirement already satisfied: colorama in ./miniconda3/envs/comet/lib/python3.12/site-packages (from sacrebleu<3.0.0,>=2.0.0->unbabel-comet) (0.4.6)
Collecting lxml (from sacrebleu<3.0.0,>=2.0.0->unbabel-comet)
  Downloading lxml-5.2.2-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (3.4 kB)
Collecting sympy (from torch>=1.6.0->unbabel-comet)
  Downloading sympy-1.13.1-py3-none-any.whl.metadata (12 kB)
Collecting networkx (from torch>=1.6.0->unbabel-comet)
  Using cached networkx-3.3-py3-none-any.whl.metadata (5.1 kB)
Requirement already satisfied: jinja2 in ./miniconda3/envs/comet/lib/python3.12/site-packages (from torch>=1.6.0->unbabel-comet) (3.1.4)
Collecting nvidia-cuda-nvrtc-cu12==12.1.105 (from torch>=1.6.0->unbabel-comet)
  Using cached nvidia_cuda_nvrtc_cu12-12.1.105-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cuda-runtime-cu12==12.1.105 (from torch>=1.6.0->unbabel-comet)
  Using cached nvidia_cuda_runtime_cu12-12.1.105-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cuda-cupti-cu12==12.1.105 (from torch>=1.6.0->unbabel-comet)
  Using cached nvidia_cuda_cupti_cu12-12.1.105-py3-none-manylinux1_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cudnn-cu12==8.9.2.26 (from torch>=1.6.0->unbabel-comet)
  Using cached nvidia_cudnn_cu12-8.9.2.26-py3-none-manylinux1_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cublas-cu12==12.1.3.1 (from torch>=1.6.0->unbabel-comet)
  Using cached nvidia_cublas_cu12-12.1.3.1-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cufft-cu12==11.0.2.54 (from torch>=1.6.0->unbabel-comet)
  Using cached nvidia_cufft_cu12-11.0.2.54-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-curand-cu12==10.3.2.106 (from torch>=1.6.0->unbabel-comet)
  Using cached nvidia_curand_cu12-10.3.2.106-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cusolver-cu12==11.4.5.107 (from torch>=1.6.0->unbabel-comet)
  Using cached nvidia_cusolver_cu12-11.4.5.107-py3-none-manylinux1_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cusparse-cu12==12.1.0.106 (from torch>=1.6.0->unbabel-comet)
  Using cached nvidia_cusparse_cu12-12.1.0.106-py3-none-manylinux1_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-nccl-cu12==2.20.5 (from torch>=1.6.0->unbabel-comet)
  Using cached nvidia_nccl_cu12-2.20.5-py3-none-manylinux2014_x86_64.whl.metadata (1.8 kB)
Collecting nvidia-nvtx-cu12==12.1.105 (from torch>=1.6.0->unbabel-comet)
  Using cached nvidia_nvtx_cu12-12.1.105-py3-none-manylinux1_x86_64.whl.metadata (1.7 kB)
Collecting nvidia-nvjitlink-cu12 (from nvidia-cusolver-cu12==11.4.5.107->torch>=1.6.0->unbabel-comet)
  Downloading nvidia_nvjitlink_cu12-12.5.82-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting tokenizers<0.20,>=0.19 (from transformers<5.0,>=4.17->unbabel-comet)
  Downloading tokenizers-0.19.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (6.7 kB)
Collecting safetensors>=0.4.1 (from transformers<5.0,>=4.17->unbabel-comet)
  Downloading safetensors-0.4.3-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (3.8 kB)
Collecting aiohttp!=4.0.0a0,!=4.0.0a1 (from fsspec[http]>=2022.5.0->pytorch-lightning<3.0.0,>=2.0.0->unbabel-comet)
  Using cached aiohttp-3.9.5-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (7.5 kB)
Requirement already satisfied: setuptools in ./miniconda3/envs/comet/lib/python3.12/site-packages (from lightning-utilities>=0.10.0->pytorch-lightning<3.0.0,>=2.0.0->unbabel-comet) (69.5.1)
Requirement already satisfied: six>=1.5 in ./miniconda3/envs/comet/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas>=1.4.1->unbabel-comet) (1.16.0)
Requirement already satisfied: MarkupSafe>=2.0 in ./miniconda3/envs/comet/lib/python3.12/site-packages (from jinja2->torch>=1.6.0->unbabel-comet) (2.1.3)
Requirement already satisfied: charset-normalizer<4,>=2 in ./miniconda3/envs/comet/lib/python3.12/site-packages (from requests->huggingface-hub<1.0,>=0.19.3->unbabel-comet) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in ./miniconda3/envs/comet/lib/python3.12/site-packages (from requests->huggingface-hub<1.0,>=0.19.3->unbabel-comet) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in ./miniconda3/envs/comet/lib/python3.12/site-packages (from requests->huggingface-hub<1.0,>=0.19.3->unbabel-comet) (2.2.2)
Requirement already satisfied: certifi>=2017.4.17 in ./miniconda3/envs/comet/lib/python3.12/site-packages (from requests->huggingface-hub<1.0,>=0.19.3->unbabel-comet) (2024.7.4)
Collecting mpmath<1.4,>=1.1.0 (from sympy->torch>=1.6.0->unbabel-comet)
  Using cached mpmath-1.3.0-py3-none-any.whl.metadata (8.6 kB)
Collecting aiosignal>=1.1.2 (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2022.5.0->pytorch-lightning<3.0.0,>=2.0.0->unbabel-comet)
  Using cached aiosignal-1.3.1-py3-none-any.whl.metadata (4.0 kB)
Requirement already satisfied: attrs>=17.3.0 in ./miniconda3/envs/comet/lib/python3.12/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2022.5.0->pytorch-lightning<3.0.0,>=2.0.0->unbabel-comet) (23.2.0)
Collecting frozenlist>=1.1.1 (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2022.5.0->pytorch-lightning<3.0.0,>=2.0.0->unbabel-comet)
  Using cached frozenlist-1.4.1-cp312-cp312-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (12 kB)
Collecting multidict<7.0,>=4.5 (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2022.5.0->pytorch-lightning<3.0.0,>=2.0.0->unbabel-comet)
  Using cached multidict-6.0.5-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.2 kB)
Collecting yarl<2.0,>=1.0 (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2022.5.0->pytorch-lightning<3.0.0,>=2.0.0->unbabel-comet)
  Using cached yarl-1.9.4-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (31 kB)
Downloading unbabel_comet-2.2.2-py3-none-any.whl (93 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 93.1/93.1 kB 1.0 MB/s eta 0:00:00
Downloading jsonargparse-3.13.1-py3-none-any.whl (101 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 101.4/101.4 kB 945.5 kB/s eta 0:00:00
Downloading entmax-1.3-py3-none-any.whl (13 kB)
Downloading huggingface_hub-0.24.1-py3-none-any.whl (417 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 417.2/417.2 kB 1.3 MB/s eta 0:00:00
Downloading protobuf-4.25.3-cp37-abi3-manylinux2014_x86_64.whl (294 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 294.6/294.6 kB 1.3 MB/s eta 0:00:00
Downloading pytorch_lightning-2.3.3-py3-none-any.whl (812 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 812.3/812.3 kB 1.3 MB/s eta 0:00:00
Downloading sacrebleu-2.4.2-py3-none-any.whl (106 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 106.7/106.7 kB 1.0 MB/s eta 0:00:00
Downloading scipy-1.14.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (40.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 40.8/40.8 MB 915.2 kB/s eta 0:00:00
Using cached torch-2.3.1-cp312-cp312-manylinux1_x86_64.whl (779.1 MB)
Using cached nvidia_cublas_cu12-12.1.3.1-py3-none-manylinux1_x86_64.whl (410.6 MB)
Using cached nvidia_cuda_cupti_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (14.1 MB)
Using cached nvidia_cuda_nvrtc_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (23.7 MB)
Using cached nvidia_cuda_runtime_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (823 kB)
Using cached nvidia_cudnn_cu12-8.9.2.26-py3-none-manylinux1_x86_64.whl (731.7 MB)
Using cached nvidia_cufft_cu12-11.0.2.54-py3-none-manylinux1_x86_64.whl (121.6 MB)
Using cached nvidia_curand_cu12-10.3.2.106-py3-none-manylinux1_x86_64.whl (56.5 MB)
Using cached nvidia_cusolver_cu12-11.4.5.107-py3-none-manylinux1_x86_64.whl (124.2 MB)
Using cached nvidia_cusparse_cu12-12.1.0.106-py3-none-manylinux1_x86_64.whl (196.0 MB)
Using cached nvidia_nccl_cu12-2.20.5-py3-none-manylinux2014_x86_64.whl (176.2 MB)
Using cached nvidia_nvtx_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (99 kB)
Downloading torchmetrics-0.10.3-py3-none-any.whl (529 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 529.7/529.7 kB 1.0 MB/s eta 0:00:00
Downloading transformers-4.43.1-py3-none-any.whl (9.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.4/9.4 MB 791.0 kB/s eta 0:00:00
Downloading fsspec-2024.6.1-py3-none-any.whl (177 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 177.6/177.6 kB 981.1 kB/s eta 0:00:00
Downloading lightning_utilities-0.11.6-py3-none-any.whl (26 kB)
Using cached regex-2024.5.15-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (788 kB)
Downloading safetensors-0.4.3-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 942.7 kB/s eta 0:00:00
Using cached tabulate-0.9.0-py3-none-any.whl (35 kB)
Downloading tokenizers-0.19.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.6/3.6 MB 878.2 kB/s eta 0:00:00
Downloading filelock-3.15.4-py3-none-any.whl (16 kB)
Downloading lxml-5.2.2-cp312-cp312-manylinux_2_28_x86_64.whl (4.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.9/4.9 MB 703.8 kB/s eta 0:00:00
Using cached networkx-3.3-py3-none-any.whl (1.7 MB)
Downloading portalocker-2.10.1-py3-none-any.whl (18 kB)
Downloading sympy-1.13.1-py3-none-any.whl (6.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.2/6.2 MB 487.1 kB/s eta 0:00:00
Using cached aiohttp-3.9.5-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.3 MB)
Using cached mpmath-1.3.0-py3-none-any.whl (536 kB)
Downloading nvidia_nvjitlink_cu12-12.5.82-py3-none-manylinux2014_x86_64.whl (21.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.3/21.3 MB 1.2 MB/s eta 0:00:00
Using cached aiosignal-1.3.1-py3-none-any.whl (7.6 kB)
Using cached frozenlist-1.4.1-cp312-cp312-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (281 kB)
Using cached multidict-6.0.5-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (130 kB)
Using cached yarl-1.9.4-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (322 kB)
Building wheels for collected packages: sentencepiece
  Building wheel for sentencepiece (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [65 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.linux-x86_64-cpython-312
      creating build/lib.linux-x86_64-cpython-312/sentencepiece
      copying src/sentencepiece/__init__.py -> build/lib.linux-x86_64-cpython-312/sentencepiece
      copying src/sentencepiece/_version.py -> build/lib.linux-x86_64-cpython-312/sentencepiece
      copying src/sentencepiece/sentencepiece_model_pb2.py -> build/lib.linux-x86_64-cpython-312/sentencepiece
      copying src/sentencepiece/sentencepiece_pb2.py -> build/lib.linux-x86_64-cpython-312/sentencepiece
      running build_ext
      Package sentencepiece was not found in the pkg-config search path.
      Perhaps you should add the directory containing `sentencepiece.pc'
      to the PKG_CONFIG_PATH environment variable
      No package 'sentencepiece' found
      ./build_bundled.sh: 21: cmake: not found
      ./build_bundled.sh: 22: cmake: not found
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-7roc0z9z/sentencepiece_a5966f440c5f439dbca134cc732bc8ba/setup.py", line 167, in <module>
          setup(
        File "/home/denis/miniconda3/envs/comet/lib/python3.12/site-packages/setuptools/__init__.py", line 104, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/denis/miniconda3/envs/comet/lib/python3.12/site-packages/setuptools/_distutils/core.py", line 184, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "/home/denis/miniconda3/envs/comet/lib/python3.12/site-packages/setuptools/_distutils/core.py", line 200, in run_commands
          dist.run_commands()
        File "/home/denis/miniconda3/envs/comet/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/home/denis/miniconda3/envs/comet/lib/python3.12/site-packages/setuptools/dist.py", line 967, in run_command
          super().run_command(command)
        File "/home/denis/miniconda3/envs/comet/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/home/denis/miniconda3/envs/comet/lib/python3.12/site-packages/wheel/bdist_wheel.py", line 368, in run
          self.run_command("build")
        File "/home/denis/miniconda3/envs/comet/lib/python3.12/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
          self.distribution.run_command(command)
        File "/home/denis/miniconda3/envs/comet/lib/python3.12/site-packages/setuptools/dist.py", line 967, in run_command
          super().run_command(command)
        File "/home/denis/miniconda3/envs/comet/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/home/denis/miniconda3/envs/comet/lib/python3.12/site-packages/setuptools/_distutils/command/build.py", line 132, in run
          self.run_command(cmd_name)
        File "/home/denis/miniconda3/envs/comet/lib/python3.12/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
          self.distribution.run_command(command)
        File "/home/denis/miniconda3/envs/comet/lib/python3.12/site-packages/setuptools/dist.py", line 967, in run_command
          super().run_command(command)
        File "/home/denis/miniconda3/envs/comet/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/home/denis/miniconda3/envs/comet/lib/python3.12/site-packages/setuptools/command/build_ext.py", line 91, in run
          _build_ext.run(self)
        File "/home/denis/miniconda3/envs/comet/lib/python3.12/site-packages/setuptools/_distutils/command/build_ext.py", line 359, in run
          self.build_extensions()
        File "/home/denis/miniconda3/envs/comet/lib/python3.12/site-packages/setuptools/_distutils/command/build_ext.py", line 479, in build_extensions
          self._build_extensions_serial()
        File "/home/denis/miniconda3/envs/comet/lib/python3.12/site-packages/setuptools/_distutils/command/build_ext.py", line 505, in _build_extensions_serial
          self.build_extension(ext)
        File "/tmp/pip-install-7roc0z9z/sentencepiece_a5966f440c5f439dbca134cc732bc8ba/setup.py", line 87, in build_extension
          subprocess.check_call(['./build_bundled.sh', __version__])
        File "/home/denis/miniconda3/envs/comet/lib/python3.12/subprocess.py", line 413, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['./build_bundled.sh', '0.1.99']' returned non-zero exit status 127.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for sentencepiece
  Running setup.py clean for sentencepiece
Failed to build sentencepiece
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (sentencepiece)

**Comment by Denis-Kazakov** [comment]
I created a new conda environment and successfully installed sentencepiece first with `conda install -c conda-forge sentencepiece`. This was followed by other conda packages (pandas, jupyter lab), tqdm and finally COMET but got the same error.

**Comment by pavanjava** [comment]
My Python environment is 3.12.4 and sentencepiece dependency require python < 3.12 and there is a new sentencepiece 0.2.0 released when can we expect new release of commet library

```
INFO: pip is looking at multiple versions of unbabel-comet to determine which version is compatible with other requirements. This could take a while.
ERROR: Cannot install -r requirements.txt (line 1) and sentencepiece==0.2.0 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested sentencepiece==0.2.0
    unbabel-comet 2.2.2 depends on sentencepiece<0.2.0 and >=0.1.96

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

```

**Comment by Denis-Kazakov** [comment]
> My Python environment is 3.12.4 and sentencepiece dependency require python < 3.12 and there is a new sentencepiece 0.2.0 released when can we expect new release of commet library
> 
> ```
> INFO: pip is looking at multiple versions of unbabel-comet to determine which version is compatible with other requirements. This could take a while.
> ERROR: Cannot install -r requirements.txt (line 1) and sentencepiece==0.2.0 because these package versions have conflicting dependencies.
> 
> The conflict is caused by:
>     The user requested sentencepiece==0.2.0
>     unbabel-comet 2.2.2 depends on sentencepiece<0.2.0 and >=0.1.96
> 
> To fix this you could try to:
> 1. loosen the range of package versions you've specified
> 2. remove package versions to allow pip attempt to solve the dependency conflict
> ```

Thank you! I recreated the conda environment specifying python=3.11 and sentencepiece=0.1.99 and now it works fine!
